[env:m5stack-cores3]
platform = espressif32@^6.7
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
extra_scripts = pre:scripts/sanotts_extra.py
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_HAS_PSRAM
  -DDOTS_TLS_VERIFY=1
  -DDOTS_FW_VERSION=\"0.1.0\"
lib_deps =
  m5stack/M5Unified@^0.2.24
  m5stack/M5GFX@^0.2.5
  meganetaaan/M5Stack-Avatar@^0.10.0
  bblanchon/ArduinoJson@^7.2.0
  links2004/WebSockets@^2.6.1
